server:
    port : 8081
spring:
    shell:
        interactive:
            enabled: true

        script:
            spring:
                shell:
                    script: false
    datasource:
        url: jdbc:h2:mem:testdb
        initialization-mode: always
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: none

        properties:
            hibernate:
                format_sql: true

        show-sql: true


logging:
    level:
        ROOT: INFO