spring:
  shell:
    interactive:
      enabled: true

    script:
      spring:
        shell:
          script: true
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    ROOT: INFO